# Generated by Django 3.2.5 on 2021-07-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('owed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_by', to='DjangoRefresherApp.user')),
                ('owed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_to', to='DjangoRefresherApp.user')),
            ],
        ),
    ]
