# Generated by Django 3.2.5 on 2021-07-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRefresherApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
